use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::MemberId)
                            .string_len(32)
                            .not_null()
                            .default(""),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(ColumnDef::new(Member::Role).string_len(64).not_null().default(""))
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::Direction)
                            .string_len(32)
                            .not_null()
                            .default(""),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::HireDate)
                            .string_len(10)
                            .not_null()
                            .default("1970-01-01"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::WorkYears)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::MemberType)
                            .string_len(16)
                            .not_null()
                            .default("employee"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::GroupName)
                            .string_len(64)
                            .not_null()
                            .default("未分组"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::Status)
                            .string_len(16)
                            .not_null()
                            .default("active"),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(ColumnDef::new(Member::Content).text().not_null().default(""))
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::UpdatedAt)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .add_column(
                        ColumnDef::new(Member::CreatedAt)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_member_member_id")
                    .table(Member::Table)
                    .col(Member::MemberId)
                    .unique()
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(
                Index::drop()
                    .name("idx_member_member_id")
                    .table(Member::Table)
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::UpdatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::Content)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::Status)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::GroupName)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::MemberType)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::WorkYears)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::HireDate)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::Direction)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::Role)
                    .to_owned(),
            )
            .await?;
        manager
            .alter_table(
                Table::alter()
                    .table(Member::Table)
                    .drop_column(Member::MemberId)
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum Member {
    Table,
    MemberId,
    Role,
    Direction,
    HireDate,
    WorkYears,
    MemberType,
    GroupName,
    Status,
    Content,
    UpdatedAt,
    CreatedAt,
}
